#!/usr/bin/python



def options(opt):
        opt.load("waf_unit_test")
        pass
    

def configure(conf):
        conf.load("waf_unit_test")


# def post(bld):
#         print("run test loader")
#         #print (bld.get_tgen_by_name('simpletestload').bld.retval)
#         bld.exec_command(['_build/strategy/test/simpletestload.exe',  "_build/strategy/cygsimpleLib.dll"])

def build(bld):
        bld.program(
                source          = bld.path.ant_glob('*.cpp'),
                target          = 'backtestbedtest',
                features         = 'test',
                use             = ['com_interface', 'backtestbed', 'gmock']) 


       # bld.add_post_fun(post)