#!/usr/bin/python


def options(opt):
        opt.recurse('test') 
    
    

def configure(conf):
        conf.recurse('test') 
        

def build(bld):
        bld.stlib(
            source          = bld.path.ant_glob('*.cpp dynamicloader.cpp'),
            target          = 'util',
            defines         = ['_USE_W32_SOCKETS'],
            export_includes = '.',
            use             = 'com_interface') 
        bld.recurse('test') 