#!/usr/bin/python


def options(opt):
        opt.recurse('test') 
    
    

def configure(conf):
        conf.recurse('test') 
        

def build(bld):
        bld.stlib(
            source          = bld.path.ant_glob('*.cpp'),
            target          = 'util',
            export_includes = '.',
            use             = 'com_interface') 
        bld.recurse('test') 