#!/usr/bin/python


def options(opt):
        pass
    

def configure(conf):
        pass

def build(bld):
        bld(export_includes = '.',
     #    source          = bld.path.ant_glob('*.cpp', excl = 'test'),
         name = 'com_interface')