#!/usr/bin/python


def options(opt):
        pass
    

def configure(conf):
        pass

def fun(task):

    dlllibpath = task.generator.bld.get_tgen_by_name('simpleLib').link_task.outputs[0].abspath()
    task.ut_exec.append(dlllibpath)


def build(bld):
        #bld.get_tgen_by_name('simpleLib').link_task.outputs[0].abspath()
        bld.program(
                source          = bld.path.ant_glob('*.cpp'),
                target          = 'simpletestload',
                features        = 'test',
                use             = ['com_interface', 'util', 'simpleLib', 'bluemessage'],
               # ut_cwd   = bld.path.abspath(),
                ut_fun   = fun
    ) 

       # bld.add_post_fun(post)