#!/usr/bin/python



def options(opt):
        pass
    

def configure(conf):
        pass

def build(bld):
        bld.stlib(
                source          = bld.path.ant_glob('*.cpp', excl = 'test'),
                target          = 'backtestbed',
                use             =  ['com_interface', 'util']) 
        bld.recurse('test') 
